name: oman_tourist_mate_fixed
description: "Oman Tourist Mate - Tourism App"
publish_to: "none"
version: 1.0.0+1
environment:
 sdk: ">=3.3.0 <4.0.0"
dependencies:
 flutter:
   sdk: flutter
 cupertino_icons: ^1.0.8
 video_player: ^2.8.1
 flutter_markdown: ^0.7.3
 # Firebase
 firebase_core: ^3.6.0
 share_plus: ^7.0.0
 firebase_auth: ^5.3.0
 cloud_firestore: ^5.4.0
 cloud_functions: ^5.0.4
 webview_flutter: ^4.7.0
 flutter_inappwebview: ^6.0.0
 permission_handler: ^11.3.1
 webview_flutter_android: ^3.14.0
 # خرائط جوجل
 google_maps_flutter: ^2.9.0
 # الموقع والـ reverse geocoding
 geolocator: ^13.0.1
 geocoding: ^3.0.0
 url_launcher: ^6.3.0
 # المفضلة / تخزين محلي
 shared_preferences: ^2.2.3
 # Gemini
 google_generative_ai: ^0.4.6
 # HTTP
 http: ^1.2.1
 # تعدد اللغات
 flutter_localizations:
   sdk: flutter
 intl: ^0.20.2
dev_dependencies:
 flutter_test:
   sdk: flutter
 flutter_lints: ^4.0.0
 flutter_launcher_icons: "^0.13.1"
 csv: ^5.1.0
flutter:
 uses-material-design: true
 assets:
   - assets/images/oman_background.jpg
   - assets/images/rose_bg.jpg
   - assets/images/logo2.png
   - assets/images/omansplash.jpg
   - assets/images/omr_notes.jpg
   - assets/images/currency_bg.png
   - assets/images/attractions/mughsail.jpg
   - assets/hero/whales.jpg
   - assets/images/accommodations/radisson.jpg
   - assets/hero/mountains.mp4
   - assets/hero/girl.jpg
   - assets/hero/tower.jpg
   - assets/interests/shopping.jpg
   - assets/interests/heritage.jpg
   - assets/interests/nature.jpg
   - assets/interests/beach.jpg
   - assets/interests/adventure.jpg
   - assets/interests/food.jpg
   - assets/tips/header.jpg
   - assets/tips/safety.jpg
   - assets/tips/currency.jpg
   - assets/tips/etiquette.jpg
   - assets/tips/emergency.jpg
   - assets/tips/tax_refund.jpg
   # نترك الخريطة بدون ستايل حتى تبقى أسماء المدن ظاهرة (للاستخدام لاحقًا)
   - assets/map_styles/clean_oman.json
   - assets/map_styles/visit_oman_like.json
   # أيقونات
   - assets/icons/marker_city.png
   - assets/icons/sea.png
   - assets/icons/desert.png
   - assets/icons/pin.png
   - assets/icons/historic.png
   - assets/geo/oman_outline.geojson
   - assets/geo/oman_governorates.geojson
   - assets/web/oman_map.html
   - assets/web/leaflet_map.html
   - assets/web/oman_svg_map.html
   - assets/web/custom.geo.json
   - assets/web/geo/oman_governorates.geojson
   - assets/web/geo/hotosm_omn_populated_places_points_geojson.geojson
   - assets/web/oman_map_inline.html
   - assets/web/img/darbat.jpg
   - assets/web/img/darbat_1.jpg
   - assets/web/img/dhofar_hero.jpg
   - assets/web/img/mughsail.jpg
   - assets/web/img/mughsail_1.jpg
   - assets/web/img/muscat_hero.jpg
   - assets/web/img/muscat_mosque.jpg
   - assets/web/img/muscat_mosque_1.jpg
   - assets/web/img/muscat_mosque_2.jpg
   - assets/web/img/muttrah.jpg
   - assets/web/img/muttrah_1.jpg
   - assets/web/img/muttrah_2.jpg
   - assets/web/img/nizwa.jpg
   - assets/web/img/nizwa_1.jpg
   - assets/web/img/adakhliyah_hero.jpg
   # Sohar
   - assets/places/sohar/beach_1.jpg
   - assets/places/sohar/beach_2.jpg
   - assets/places/sohar/fort_1.jpg
   - assets/places/sohar/fort_2.jpg
   - assets/places/sohar/souq_1.jpg
   - assets/places/sohar/souq_2.jpg
   - assets/places/sohar/alkhater.jpg
   - assets/places/sohar/robusta.jpg
   - assets/places/sohar/mercure_sohar.jpg
   # Muscat
   - assets/places/muscat/qurum_1.jpg
   - assets/places/muscat/qurum_2.jpg
   - assets/places/muscat/muttrah_1.jpg
   - assets/places/muscat/muttrah_2.jpg
   - assets/places/muscat/muttrah_3.jpg
   - assets/places/muscat/qasr_alalm.jpg
   - assets/places/muscat/hotel.jpg
   - assets/places/muscat/resturant_muscat.jpg
   - assets/places/muscat/qaha.jpg
   # Nizwa / Bahla
   - assets/places/nizwa/fort_1.jpg
   - assets/places/bahla/fort_1.jpg
   # Salalah
   - assets/places/salalah/beach_1.jpg
   - assets/places/salalah/beach_2.jpg
   - assets/places/salalah/al_baleed.jpg
   - assets/places/salalah/haffa_beach.jpg
   - assets/places/salalah/millennium_resort.jpg
   - assets/places/salalah/lit_lin.jpg 
   - assets/places/salalah/corniche.jpg
   - assets/places/salalah/header.jpg
   - assets/places/salalah/55coffee.jpg
   # Desert generic
   - assets/places/desert/wahiba_1.jpg
   - assets/places/desert/wahiba_2.jpg
   - assets/places/desert/empty_1.jpg
   - assets/places/desert/empty_2.jpg
   - assets/places/generic/placeholder.jpg
   #flight
   - assets/airlines/oman_air.jpg
   - assets/airlines/salam_air.jpg
   - assets/airlines/lounge.jpg
   - assets/airlines/meet_assist.jpg
   - assets/airlines/home_checkin.jpg
   - assets/airlines/hero.jpg
   #hotels
   - assets/hotels/hero.jpg
   -  assets/hotels/shangrila.jpg
   -  assets/hotels/sheraton.jpg
   -  assets/hotels/radisson.jpg
   - assets/hotels/muscat/kempinski.jpg
   - assets/hotels/muscat/grandhyatt.jpg
   - assets/hotels/muscat/crowneplaza.jpg
   - assets/hotels/muscat/intercontinental.jpg
   - assets/hotels/muscat/movenpick.jpg
   - assets/hotels/muscat/avani.jpg
   - assets/hotels/muscat/wyndham.jpg
   - assets/images/accommodations/kempinski.jpg
   - assets/images/accommodations/grandhyatt.jpg
   - assets/images/accommodations/crowneplaza.jpg
   - assets/images/accommodations/intercontinental.jpg
   - assets/images/accommodations/movenpick.jpg
   - assets/images/accommodations/avani.jpg
   - assets/images/accommodations/wyndham.jpg
   #tours
   - assets/tours/nature.jpg
   - assets/tours/hero_tours.jpg
   - assets/tours/desert.jpg
   - assets/tours/dhow.jpg
   - assets/tours/helicopter.jpg
   #attractions
   - assets/attractions/hero.jpg
   - assets/attractions/al_hoota_cave.jpg
   - assets/attractions/opera_house.jpg
   - assets/attractions/national_museum.jpg
   #transports
   - assets/transport/airport.jpg
   #dining
   - assets/dining/alaqr.jpg
   - assets/dining/oman_food.jpg
   - assets/dining/global.jpg
   - assets/dining/luxury.jpg
   - assets/dining/hero.jpg
   - assets/data/accommodations.csv
   - assets/data/attractions.csv
fonts:

  - family: ElMessiri

    fonts:

      - asset: assets/fonts/ElMessiri-Regular.ttf

        weight: 400

      - asset: assets/fonts/ElMessiri-Bold.ttf

        weight: 700

  - family: Montserrat

    fonts:

      - asset: assets/fonts/Montserrat-Regular.ttf

      - asset: assets/fonts/Montserrat-Bold.ttf

  - family: Tajawal

    fonts:

      - asset: assets/fonts/Tajawal-Regular.ttf

      - asset: assets/fonts/Tajawal-Bold.ttf

  - family: AlexBrush

    fonts:

      - asset: assets/fonts/AlexBrush-Regular.ttf
 

flutter_icons:
 android: true
 ios: true
 image_path: "assets/images/logo.png"
 android_adaptive_icon_background: "#FFFFFF"
 android_adaptive_icon_foreground: "assets/images/logo.png"